### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by fabiofumarola** [DataToKnowledge/wheretolive.it#2]
1. When I clone the project in the folder `wtlElasticUI` there isn't data.
2. following the installing guide I made the following steps, but without success and i got the error `Warning: Task "typescript:dist" not found. Use --force to continue.`
   
   ```
   cd wtlElasticUI
   npm install
   grunt typescript:dist 
   grunt uglify
   ```
3. When I tried to run the website locally I got error since it cannot find required modules

**Comment by fabiofumarola** [comment]
When you submit an update you should clone the project into another folder and do all the steps to verify that everything works

**Comment by fabiana001** [comment]
I have just forgot to tell you to clone the project with submodules. 

Try this command: `git clone --recursive git@github.com:DataToKnowledge/wheretolive.it.git`
If you yet cloned the repo see [here](http://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules).

**Comment by fabiana001** [comment]
Let me know if you are able to run the project correctly
